# syntax=docker/dockerfile:1.2
FROM node:14 as builder
FROM node:alpine
ENV NODE_OPTIONS=--openssl-legacy-provider
ARG TRIVY_VERSION=0.18.3
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
RUN wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz \
  && tar zxvf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz \
  && mv trivy /usr/local/bin/

RUN trivy --download-db-only

EXPOSE 80
COPY --from=0 /app/build /usr/share/nginx/html